SELECT HISTORY_ID, CAR_ID, 
        DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE, 
        SUBSTRING(END_DATE, 1, 10) AS END_DATE,
CASE WHEN DATEDIFF(END_DATE, START_DATE) < 29 THEN '단기 대여' 
ELSE '장기 대여' END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE LIKE '2022-09-%'
ORDER BY HISTORY_ID DESC;