SELECT BO.BOOK_ID, AU.AUTHOR_NAME, SUBSTRING(BO.PUBLISHED_DATE, 1, 10) AS PUBLISHED_DATE FROM BOOK BO
INNER JOIN AUTHOR AU ON BO.AUTHOR_ID = AU.AUTHOR_ID
WHERE BO.CATEGORY = '경제'
ORDER BY BO.PUBLISHED_DATE;